### PR TITLE
geo_to_hca: Updated hca template to reflect schema updates (treatment protocol)

### PR DESCRIPTION
**Pull request by ami-day**
Updated geo_to_hca template to reflect schema updates (Release from staging to master: https://github.com/HumanCellAtlas/metadata-schema/pull/1456):

- Treatment protocol method
- Treatment protocol ontology
- Treatment protocol target pathway ontology

- [x] Update the template spreadsheet
- [x] Test the updated template spreadsheet in ingest - does it validate using a test dataset?

### CODE REVIEW

**Comment by amnonkhen** [comment]
@ami-day @ESapenaVentura has this been done?

**Comment by idazucchi** [comment]
waiting for the test data to be approved before mergin the new hca spreadsheet

**Review by amnonkhen — CHANGES_REQUESTED** [review]
xlsx template needs to be updated after schema change is pushed to master.

**Comment by MightyAx** [comment]
Treatment protocol has been deployed

**Comment by MightyAx** [comment]
@ami-day please link the PR with the updated spreadsheet.

**Comment by MightyAx** [comment]
@ESapenaVentura 👋

**Review by ESapenaVentura — CHANGES_REQUESTED** [review]
The schema tab is outdated, it should be replaced by the following values:

```
https://schema.humancellatlas.org/type/protocol/sequencing/10.1.0/sequencing_protocol
https://schema.humancellatlas.org/type/protocol/sequencing/6.3.1/library_preparation_protocol
https://schema.humancellatlas.org/type/protocol/imaging/11.4.0/imaging_protocol
https://schema.humancellatlas.org/type/protocol/imaging/2.3.0/imaging_preparation_protocol
https://schema.humancellatlas.org/type/protocol/biomaterial_collection/3.2.0/ipsc_induction_protocol
https://schema.humancellatlas.org/type/protocol/biomaterial_collection/3.1.0/enrichment_protocol
https://schema.humancellatlas.org/type/protocol/biomaterial_collection/6.2.0/dissociation_protocol
https://schema.humancellatlas.org/type/protocol/biomaterial_collection/2.2.0/differentiation_protocol
https://schema.humancellatlas.org/type/protocol/biomaterial_collection/9.2.0/collection_protocol
https://schema.humancellatlas.org/type/protocol/biomaterial_collection/2.1.0/aggregate_generation_protocol
https://schema.humancellatlas.org/type/protocol/analysis/9.2.0/analysis_protocol
https://schema.humancellatlas.org/type/protocol/7.1.0/protocol
https://schema.humancellatlas.org/type/project/17.0.0/project
https://schema.humancellatlas.org/type/process/sequencing/5.1.0/library_preparation_process
https://schema.humancellatlas.org/type/process/9.2.0/process
https://schema.humancellatlas.org/type/file/2.5.0/supplementary_file
https://schema.humancellatlas.org/type/file/9.5.0/sequence_file
https://schema.humancellatlas.org/type/file/3.5.0/reference_file
https://schema.humancellatlas.org/type/file/2.5.0/image_file
https://schema.humancellatlas.org/type/file/6.5.0/analysis_file
https://schema.humancellatlas.org/type/biomaterial/10.5.0/specimen_from_organism
https://schema.humancellatlas.org/type/biomaterial/11.3.0/organoid
https://schema.humancellatlas.org/type/biomaterial/3.3.0/imaged_specimen
https://schema.humancellatlas.org/type/biomaterial/15.6.0/donor_organism
https://schema.humancellatlas.org/type/biomaterial/13.3.0/cell_suspension
https://schema.humancellatlas.org/type/biomaterial/15.1.0/cell_line
https://schema.humancellatlas.org/type/protocol/biomaterial_collection/1.0.0/treatment_protocol
```
In the future, we may want to think about how to generate these programmatically. It's relatively easy by looking into the "latestSchema" endpoint in our API and selecting type, but it also requires some manual cleaning (some old schemas we don't really use anymore)

And minor things in the treatment protocol tab:
- `Differentiation media` should be `Treatment media`
-  Description of the ontologised fields (target_pathway mainly) should have the descriptions according to what the schema says (currently, they are pointing to ontologies and terms from the method field)

**Comment by ami-day** [comment]
Made updates
https://github.com/ebi-ait/geo_to_hca/tree/update_template_with_treatment_protocol

**Comment by ami-day** [comment]
Awaiting review by @amnonkhen and @ESapenaVentura

**Comment by MightyAx** [comment]
PR that needs reviewing: ebi-ait/geo_to_hca#37

**Review by ESapenaVentura — APPROVED** [review]
LGTM

**Comment by idazucchi** [comment]
open [PR](https://github.com/ebi-ait/geo_to_hca/pull/37)

**Review by amnonkhen — CHANGES_REQUESTED** [review]
please upgrade the version

**Review by idazucchi — CHANGES_REQUESTED** [review]
There are two things I would change
- add the reagent module to the template. It's useful to have all the possible fields in the template rather than having to double check the schema
- the example and description don't match the schema for the ontology fields (both method and target pathway). These fields are helpful to understand the metadata spreadsheet and will be user-facing once we start displaying the metadata spreadsheet in the browser

**Comment by ami-day** [comment]
> There are two things I would change
> 
> * add the reagent module to the template. It's useful to have all the possible fields in the template rather than having to double check the schema
> * the example and description don't match the schema for the ontology fields (both method and target pathway). These fields are helpful to understand the metadata spreadsheet and will be user-facing once we start displaying the metadata spreadsheet in the browser

Thanks, I have made the relevant updates

**Review by amnonkhen — APPROVED** [review]

**Pull request merged**
